### ISSUE TITLE
Can't turn on Dolby while using simple music player

### ISSUE THREAD

**Issue by Gamer750** [FossifyOrg/Music-Player#26] opened 2024-02-20 11:13 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Music-Player/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 6

### Affected device model

Lenovo 

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Turn on the Dolby in the phone

### Expected behavior

Dolby should be on

### Actual behavior

Not able to turn on Dolby while using simple music player

### Screenshots/Screen recordings

<img alt="251177727-f07a6cf3-3df3-4fd9-9582-7016b5f7599f" src="https://github.com/FossifyOrg/Music-Player/assets/141329708/68141fcc-f49c-4616-9f32-f142a8da9082" width=281 />

**Comment by Aga-C** [comment] 2024-02-20 12:06
Please fill out the template properly.

**Comment by Aga-C** [comment] 2024-09-20 16:35
As a bug wasn't confirmed on the newer Android versions, I close this issue because we are [dropping support for Android 6](https://github.com/orgs/FossifyOrg/discussions/241). If someone encounters this bug on at least Android 8, please let us know.

**Closed** 2024-09-20 16:35 UTC
Labels: device/software specific, bug, needs triage
