### ISSUE TITLE
Setting to select directories to include in music or media scanning

### ISSUE THREAD

**Issue by nathanzachary** [FossifyOrg/Music-Player#98] opened 2024-10-21 18:09 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I would like to see a setting to choose the directories to scan for music files, instead of having the application scan all directories.

### Why do you want this feature?

This feature will limit the scope of the application search and scan, and will likely reduce the time needed for rescans.

**Comment by Aga-C** [comment] 2024-10-21 18:38
It's a duplicate of https://github.com/FossifyOrg/Music-Player/issues/59.

**Closed** 2024-10-21 18:38 UTC
Labels: feature request, needs triage
