### ISSUE TITLE
Scanning media takes tlo long

### ISSUE THREAD

**Issue by BugReportI** [FossifyOrg/Music-Player#91] opened 2024-09-14 11:14 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Music-Player/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Music-Player/issues) or [closed](https://github.com/FossifyOrg/Music-Player/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Music-Player/discussions) or [closed](https://github.com/FossifyOrg/Music-Player/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Music-Player/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

LineageOS 21

### Affected device model

Sony Xperia 1 V

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Go to menu.
2. Press rescan media.

### Expected behavior

It should not take too long.

### Actual behavior

It takes more than 10 minutes to finish scan.

### Additional information

I am rooted with Magisk 27.0.

**Comment by naveensingh** [comment] 2024-09-14 11:17
How many audio files do you have?

**Comment by BugReportI** [comment] 2024-09-14 11:30
It is showing 549 in Fossify Music Player

I could reduce that if I could exclude the SD card from being scanned by Fossify Music Player.

Is there is a way to do this? 

So I can test to see if it reduces the time for the scan.

**Comment by naveensingh** [comment] 2024-09-14 11:35
> It is showing 549 in Fossify Music Player

10 minutes for just 549 files is very odd. Are you sure this isn't the same issue as https://github.com/FossifyOrg/Music-Player/issues/90 where the scanning notification is just stuck?

**Comment by BugReportI** [comment] 2024-09-14 11:42
> > It is showing 549 in Fossify Music Player
> 
> 10 minutes for just 549 files is very odd. Are you sure this isn't the same issue as #90 where the scanning notification is just stuck?

I do not think it is the same because the app should show scanning bar at the top in app while it is scanning.

I assume it is finished, since it is not showing that bar.

**Comment by BugReportI** [comment] 2024-09-14 11:48
If these two issues are the same it is fine to merge them into one issue

**Comment by naveensingh** [comment] 2024-09-14 11:58
> Is there is a way to do this?

Kind of. You can long press a folder and tap exclude to add it to the excluded folders list.

Looking at the current implementation, both these issues seem to have the same root cause but I I'm keeping both open until this is confirmed.

**Comment by BugReportI** [comment] 2024-09-14 12:39
I removed the folders with lots of audio in it and it seems to still be running currently at 25 minutes.

I am using the time shown on the notification. If it is correct it should not take this long to finish scan.

**Comment by naveensingh** [comment] 2024-09-14 12:43
Closing this as a duplicate of https://github.com/FossifyOrg/Music-Player/issues/90

**Closed by naveensingh** 2024-09-14 12:43 UTC
Labels: bug, needs triage
